Replace travis with CircleCI
evolvedbinary/jdita pull request #119
Opened 2023-12-11 14:19 UTC by marmoure

This is a minimal config to replace TravisCI with CircleCI.
This PR does not include `coveralls` as it will be added in another PR in the future.
[Coversall](https://www.npmjs.com/package/coveralls) is responsible for showing the code coverage in a nice web UI, we had to remove it as it was relying on TravisCI.
https://github.com/evolvedbinary/jdita/blob/cab9e3a11a18b2d79d1ad1a802b34002cb0c36c3/package.json#L16

2023-12-11 14:48 UTC, adamretter requested changes
I think we can simplify this. Maybe also consider using the CircleCI Orb for Node.js to simplify things further, e.g.:

```yaml
version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:12.13.1
    steps:
      - checkout
      - node/install-packages
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
```

2023-12-11 14:48 UTC, adamretter commented on .circleci/config.yml
> +      - run: yarn coverage
Should this be `yarn test` ?

2023-12-11 14:48 UTC, adamretter commented on .circleci/config.yml
> +executors:
The executors can just be inline for now, we only need move them to their own section if we are going to reuse them for other jobs. As we only have one job we don't need it to be separate. So the following is enough in the job.

```
jobs:
  build-and-test:
  docker:
     - image: cimg/node:16.10
    steps:
      - checkout
      - run: yarn install
      - run: yarn coverage
```

2023-12-11 14:48 UTC, adamretter commented on .circleci/config.yml
> +  node-executor:
Sometimes you are naming with `-` and sometimes with `_`. Can you choose one and stick with it please? The CircleCI examples seem to use `-`, so perhaps use that one?

2023-12-11 14:48 UTC, adamretter commented on .circleci/config.yml
> +      - image: circleci/node:12
We should be specific about which version of Node, e.g. `cimg/node:12.13.1`

2023-12-11 14:50 UTC, adamretter commented
> [Coversall](https://www.npmjs.com/package/coveralls) is responsible for showing the code coverage in a nice web UI, we had to remove it as it was relying on TravisCI.

As far as I am aware, it is not at all related to Travis CI. What was the problem that you were seeing?

2023-12-11 15:10 UTC, marmoure commented on .circleci/config.yml
> +      - run: yarn coverage
`yarn test` is included in `yarn coverage`
  https://github.com/evolvedbinary/jdita/blob/cab9e3a11a18b2d79d1ad1a802b34002cb0c36c3/package.json#L15C1-L15C1

2023-12-11 15:15 UTC, marmoure commented
> > [Coversall](https://www.npmjs.com/package/coveralls) is responsible for showing the code coverage in a nice web UI, we had to remove it as it was relying on TravisCI.
> 
> As far as I am aware, it is not at all related to Travis CI. What was the problem that you were seeing?

@adamretter when i checked the web ui https://coveralls.io/github/evolvedbinary/jdita
It said running the build via `travis-ci-com` this is what made me say it's dependent on travis-ci
Also when we try to run it locally it throws an error about the missing travis-ci token

2023-12-12 09:52 UTC, adamretter commented
@marmoure From the node coveralls documentation it says that it supports CircleCI - https://github.com/nickmerwin/node-coveralls#circleci-orb, is there anything else stopping you from fixing this?

2023-12-12 10:15 UTC, marmoure commented
> @marmoure From the node coveralls documentation it says that it supports CircleCI - https://github.com/nickmerwin/node-coveralls#circleci-orb, is there anything else stopping you from fixing this?

No nothing is stopping us from doing that.
We wanted to submit a minimal PR that we are sure that it would work so we have a stable CI to begin with then we can start trying to add `coversall` to it

2023-12-12 10:27 UTC, adamretter commented
@marmoure Ah okay, understood. I will merge this, and then please send a follow-up PR with Coveralls reinstated.

2023-12-12 10:28 UTC, adamretter commented
@marmoure Just before I merge, I note you haven't added the CI Badge to the `README.md`. Can you do so please?

2023-12-12 10:44 UTC, marmoure commented
@adamretter We opted to using the SVG style for the Circle CI badge
Which one do you prefer?

`svg` version

![image](https://github.com/evolvedbinary/jdita/assets/30597211/8a819489-c5b4-4ef3-ad36-a6f18ba6a3e9)


`shield` version

![image](https://github.com/evolvedbinary/jdita/assets/30597211/52bacdfa-0ae6-49c5-acac-ef48840bfde6)

2023-12-12 11:51 UTC, adamretter commented
@marmoure Yes, SVG style is the better one.

2023-12-12 11:51 UTC, merged