Improve README.MD documentation and badges
evolvedbinary/jdita pull request #121
Opened 2023-12-12 18:22 UTC by adamretter

Some small tweaks to the documentation, and improves the badges in the documentation.

2023-12-12 19:43 UTC, marmoure requested changes
just a small change to pass the CI

2023-12-12 19:43 UTC, marmoure commented on package.json
> +    "yarn": ">=1.22.21 <2"
This yarn limitation is falling in CI
[1/5] Validating package.json...
error jdita@0.2.4: The engine "yarn" is incompatible with this module. Expected version ">=1.22.21 <2". Got "1.22.18"
error Found incompatible module.

This should be 
```
"yarn": ">=1.22.18 <2"
```

2023-12-12 21:16 UTC, adamretter commented on package.json
> +    "yarn": ">=1.22.21 <2"
I used the version of `yarn` that was recently added to the build instructions in the `README.md` - were those instructions wrong then?

2023-12-12 21:21 UTC, marmoure commented on package.json
> +    "yarn": ">=1.22.21 <2"
No,we didn't specify which version of yarn in the CI config

The one we used locally was 1.22.21
and that's what we noted in the Readme

2023-12-12 21:28 UTC, adamretter commented on package.json
> +    "yarn": ">=1.22.21 <2"
@marmoure I think we are talking at cross-purposes!
* The `README.md` as set out by yourself and Alex says to use Yarn `1.22.21`
* In this PR I have updated the `package.json` to require at least Yarn `1.22.21` (therefore matching the `README.md`)

So why in the previous CI PR did we use Yarn 1.22.18?

2023-12-12 21:45 UTC, marmoure commented on package.json
> +    "yarn": ">=1.22.21 <2"
In the previous CI PR we used 
```
     - image: cimg/node:12.13.1
```
This docker image from circle CI uses yarn 1.22.18
We did not specify which yarn version to be used in CI.
I think we should specify an older version of yarn in the readme


PS: even in our local machine we never install a specific version of yarn as it's all managed by `nvm`, it installs the appropriate version according to your desired Nodejs version

2023-12-12 22:33 UTC, adamretter commented on package.json
> +    "yarn": ">=1.22.21 <2"
I think just relying on some random version in CI or on your local host is a very bad plan!

We must know which version we need, and we must document it. We should then use that both in CI and locally.

As it was documented that we use version 1.22.21, I would suggest that we update CI to use that. Otherwise, the other option is to change the documentation, and what you have installed locally to move backwards to version 1.22.18.

2023-12-13 08:53 UTC, plutonik-a approved these changes

2023-12-13 08:53 UTC, plutonik-a commented on package.json
> +    "yarn": ">=1.22.21 <2"
The mismatch of documented Yarn versions and used Yarn versions has now been fixed with https://github.com/evolvedbinary/jdita/pull/122 by specifying the version to `v1.22.21` as noted in the README.

2023-12-19 11:05 UTC, merged