Specify yarn version to 1.22.21 in the CI
evolvedbinary/jdita pull request #122
Opened 2023-12-13 08:47 UTC by marmoure

The CI was using a docker image with a set version of yarn, we changed that to a specific version matching the README and the local development environment.
As discussed in #121.

2023-12-13 10:50 UTC, plutonik-a approved these changes

2023-12-13 11:23 UTC, marmoure commented on .circleci/config.yml
> +      - run: yarn install
@adamretter Yes this looks much better, the PR is ready now

2023-12-14 06:13 UTC, adamretter requested changes
I don't understand why you have changed the code that I provided you.

1. Why have checkout moved to 2nd position?
2. Why do we now suddenly need `node/install-packages` ?

2023-12-19 10:57 UTC, adamretter approved these changes
LGTM

2023-12-19 10:57 UTC, merged