Feature "XDita Serialization of the AST" (#2731)
evolvedbinary/jdita pull request #136
Opened 2024-02-07 17:47 UTC by plutonik-a

### Purpose of this PR

//TODO

### How to test this PR

//TODO

---
**NOTE** 
This branch was branched from #134 simplify the development.  
https://github.com/evolvedbinary/jdita/pull/134 should be merged to [main](https://github.com/evolvedbinary/jdita/tree/main) first and then this branch needs to be rebased on main.

2024-04-03 15:17 UTC, adamretter requested changes
There are some changes around es-lint that don't seem like they should be in this PR. Also we might need to discuss the serialization of the XML as there seems to be some duplication.

2024-04-03 15:17 UTC, adamretter commented on README.md
> +The generated XML will contain all XML nodes, their text content, and their attributes (`CDATA` is currently not processed).
text is a node type! How about:
`The generated XML will faithfully contain all XML nodes apart from `CDATA` which is currently unsupported.`
We should also add a new task for adding CDATA support please!

2024-04-03 15:17 UTC, adamretter commented on README.md
> +    const res = serializeToXML(result, true).join('');
`res` seems to be unused! Is this correct?

2024-04-03 15:17 UTC, adamretter commented on packages/lwdita-ast/nodes/base.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Why change this to an inline commend?

2024-04-03 15:17 UTC, adamretter commented on packages/lwdita-ast/nodes/base.ts
> +   * @param depth - The node's level within the document tree, needed for indentation, by default set to root level "0"
`to root level "0"` -> `to root level, i.e.: 0`

2024-04-03 15:17 UTC, adamretter commented on packages/lwdita-ast/nodes/base.ts
> +   * @param indent - The indentation flag as a Boolean type, for an optional indentation of the outputXML
`outputXML` -> `output XML`

2024-04-03 15:17 UTC, adamretter commented on packages/lwdita-ast/nodes/text.ts
> +    const lineEnd = indent ? '\n' : '';
Does this match - https://www.w3.org/TR/xml/#sec-line-ends

2024-04-03 15:17 UTC, adamretter commented on packages/lwdita-xdita/converter.ts
> +  const outStream: XMLTag[] = [];
Is output stream an array of XMLTag objects? If so that doesn't seem like a stream to me! We should discuss this...

2024-04-03 15:17 UTC, adamretter commented on packages/lwdita-xdita/converter.ts
> +  return (outStream);
`return (outStream);` -> `return outStream;`

2024-04-03 15:17 UTC, adamretter commented on packages/lwdita-xdita/example.ts
> + * TODO: Implement missing handling of newlines and spaces bewtween tags in the input xml,
This sounds serious. Does this need to be addressed?

2024-04-03 15:17 UTC, adamretter commented on packages/lwdita-xdita/utils.ts
> + * TODO: Get file name info from input XML
I think these 3 TODO need to be addressed?

2024-04-03 15:17 UTC, adamretter commented on packages/lwdita-xdita/visitor.ts
> +  depth: number;
Keeping the `depth` and `indent` here for every XML Tag seems unnecessary. These variables only need to be kept once in the serializer.

2024-04-03 15:17 UTC, adamretter commented on packages/lwdita-xdita/visitor.ts
> +    const tab = `  `;
Why is the indentation characters defined both here and in `lwdita-ast/nodes/text.ts`? It should be defined only once in the serializer.

2024-04-03 15:17 UTC, adamretter commented on packages/lwdita-xdita/visitor.ts
> +    const lineEnd = this.indent ? '\n' : '';
Why is the EOL character defined both here and in `lwdita-ast/nodes/text.ts`? It should be defined only once in the serializer.

2024-04-03 15:17 UTC, adamretter commented on packages/lwdita-xdita/visitor.ts
> + * TODO change this an array or any kind of method for saving the output
Is this TODO still valid?

2024-04-04 09:21 UTC, marmoure commented on README.md
> +The serialization function contains an option for indenting the output with 2 spaces according to the level of the node tag level and adding a newline after each tag.
Using LF, `\n`, Should we add a feature to check for platform and adjust the line break accordingly.

2024-04-04 09:27 UTC, marmoure commented on README.md
> +    const res = serializeToXML(result, true).join('');
Resolved in f0f4bbd6d834809a2c2ba6a65caa0f507b23eaf7

2024-04-04 09:27 UTC, marmoure commented on README.md
> +The generated XML will contain all XML nodes, their text content, and their attributes (`CDATA` is currently not processed).
Resolved in c112a7554f3f066d9636cb42a4be2d8a2130af54

2024-04-04 09:27 UTC, marmoure commented on README.md
> +When set the second parameter to false, the output will be generated in one line.
Resolved in c112a7554f3f066d9636cb42a4be2d8a2130af54

2024-04-04 09:27 UTC, marmoure commented on README.md
> +The serialization function contains an option for indenting the output with 2 spaces according to the level of the node tag level and adding a newline after each tag.
Resolved in c112a7554f3f066d9636cb42a4be2d8a2130af54

2024-04-04 09:27 UTC, marmoure commented on README.md
> +The full example with an additional option for serializing the JDita object back into XML can be found in file [example.ts](packages/lwdita-xdita/example.ts).
Resolved in c112a7554f3f066d9636cb42a4be2d8a2130af54

2024-04-04 09:27 UTC, marmoure commented on README.md
> +### Basic example
Resolved in c112a7554f3f066d9636cb42a4be2d8a2130af54

2024-04-04 09:27 UTC, marmoure commented on README.md
> +yarn add @evolvedbinary/lwdita-ast
Resolved in ae7ce3dc34ed4aa338c78f197ab6125e4b3974a5

2024-04-04 09:28 UTC, marmoure commented on .gitignore
> +out/*
Resolved in ed365998d9b6fd16782c37e89c1594321f8700d7

2024-04-04 09:28 UTC, marmoure commented on .eslintrc
> +    // ,
Resolved in 7aa3a70d8e155e02544b564cfb9d49a1740552f0

2024-04-04 09:28 UTC, marmoure commented on README.md
> +npm install --save @evolvedbinary/lwdita-ast
Resolved in https://github.com/evolvedbinary/jdita/commit/ae7ce3dc34ed4aa338c78f197ab6125e4b3974a5

2024-04-04 09:39 UTC, marmoure commented on README.md
> +The serialization function contains an option for indenting the output with 2 spaces according to the level of the node tag level and adding a newline after each tag.
>XML serialization that are commonly see is either 4 spaces or tab character. I think we should make this configurable, but default to 4 spaces

Resolved in fc71354d0985087adb9f6f6b39acbe70bc68f762

2024-04-04 09:54 UTC, marmoure commented on packages/lwdita-ast/nodes/base.ts
> +   * @param depth - The node's level within the document tree, needed for indentation, by default set to root level "0"
Resolved in [9f57a9f](https://github.com/evolvedbinary/jdita/commit/9f57a9fb408d5e41a7b92ff5b35b8dfc897f31d5)

2024-04-04 09:54 UTC, marmoure commented on packages/lwdita-ast/nodes/base.ts
> +   * @param indent - The indentation flag as a Boolean type, for an optional indentation of the outputXML
Resolved in [9f57a9f](https://github.com/evolvedbinary/jdita/commit/9f57a9fb408d5e41a7b92ff5b35b8dfc897f31d5)

2024-04-04 10:04 UTC, marmoure commented on packages/lwdita-xdita/converter.ts
> +  return (outStream);
Resolved in 1e25d16b5eb30b8d7288bd5aacc0ef6cbfff29fe

2024-04-04 10:09 UTC, marmoure commented on packages/lwdita-xdita/utils.ts
> + * TODO: Get file name info from input XML
The `storeOutputXML` function is not something we should focus on, it was only made for example.
This code is meant to run on the backend, which we are trying to stay away from, and some of these TODOs will be resolved in upcoming task of saving the `xdita` file, they are not relevant at the moment.

2024-04-08 09:41 UTC, plutonik-a commented on packages/lwdita-ast/nodes/base.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
@adamretter Catching up on this: Should we move handling the `eslint` handling into a separate PR like @marmoure suggested?

2024-04-08 13:51 UTC, plutonik-a commented on packages/lwdita-xdita/converter.ts
> +  const outStream: XMLTag[] = [];
@adamretter 
I agree, the word stream is misleading here.  I have updated the return value and the TSDoc header accordingly with https://github.com/evolvedbinary/jdita/commit/ccf2baea5d94037c68f84badf2c3f0e1ca4b8f6a.

2024-04-08 14:12 UTC, plutonik-a commented on packages/lwdita-xdita/visitor.ts
> + * TODO change this an array or any kind of method for saving the output
I think it's obsolete and have removed it with c7ebac2.

2024-04-08 14:15 UTC, plutonik-a commented on packages/lwdita-xdita/visitor.ts
> +  depth: number;
This will be fixed by @marmoure, as he has already prepared a solution.

2024-04-08 14:15 UTC, plutonik-a commented on packages/lwdita-xdita/visitor.ts
> +    const tab = `  `;
This will be fixed by @marmoure, as he has already prepared a solution.

2024-04-08 14:15 UTC, plutonik-a commented on packages/lwdita-xdita/visitor.ts
> +    const lineEnd = this.indent ? '\n' : '';
This will be fixed by @marmoure, as he has already prepared a solution.

2024-04-09 08:39 UTC, adamretter commented on packages/lwdita-ast/nodes/base.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
@plutonik-a It seems to me that the `eslint` errors were not created in this PR, if they existed, it seems they were there before this PR. Is that correct? If so, as they are not the topic of this PR, they should be in a separate PR focused on that topic instead.

2024-04-09 09:18 UTC, plutonik-a commented on packages/lwdita-ast/nodes/base.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
@adamretter 
Yes, the `eslint` errors and their configurations (the inline comments) have existed before this PR. 
In the previous documentation PR https://github.com/evolvedbinary/jdita/pull/133 we mistakenly moved  the `eslint` configurations into the comment headers as private remarks, which of course made them useless for `eslint`.
I will remove these "rollback" fixes from this PR into a new PR.

2024-04-09 10:30 UTC, plutonik-a commented on .gitignore
> +out/*
@adamretter 
I think this is still needed: When running command `yarn example` for transforming the example document, you will produce an xml file `./out/output.xml`, and this change will then appear in the revision. 
I would like to revert this commit and keep the gitignore rule.

2024-04-09 10:45 UTC, plutonik-a commented on packages/lwdita-ast/nodes/base.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
I have reverted the relevant commits (8a1d16d, 1c340ee) and reinstated the former state with d9beb4d and fabd9ec.

2024-04-09 11:45 UTC, plutonik-a commented on packages/lwdita-ast/nodes/base.ts
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
And the promised PR is here: https://github.com/evolvedbinary/jdita/pull/150

2024-04-15 14:52 UTC, marmoure commented on packages/lwdita-xdita/visitor.ts
> +  depth: number;
Solved in [627edd7](https://github.com/evolvedbinary/jdita/pull/136/commits/627edd76dfb49fc828fdbb06f10510e1425fb461)
And in [f77e7c2](https://github.com/evolvedbinary/jdita/pull/136/commits/f77e7c2a3e14aae9bfef9b95ba908fb0c86b95f7)

2024-04-15 14:56 UTC, marmoure commented on packages/lwdita-xdita/visitor.ts
> +    const tab = `  `;
Fixed in [8366b85](https://github.com/evolvedbinary/jdita/pull/136/commits/8366b85b3d3c5b5d4de4b812ffdf820392738536)

2024-04-15 14:56 UTC, marmoure commented on packages/lwdita-xdita/visitor.ts
> +    const lineEnd = this.indent ? '\n' : '';
Fixed in [8366b85](https://github.com/evolvedbinary/jdita/pull/136/commits/8366b85b3d3c5b5d4de4b812ffdf820392738536)

2024-04-16 15:38 UTC, plutonik-a commented on .gitignore
> +out/*
I have reinstated the gitignore to ignore the output folder, as explained above. Fixed with 3718103

2024-04-22 14:36 UTC, merged